#!/usr/bin/env php
<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2016 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: yunwuxin <448901948@qq.com>
// +----------------------------------------------------------------------

namespace think;
// 定义应用目录
define('APP_PATH', __DIR__ . '/app/');
// 加载基础文件
require __DIR__ . '/thinkphp/base.php';

// 执行应用
Container::get('app', [APP_PATH])->initialize();
Console::init();